# Generated by Django 5.0.2 on 2024-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Course Name')),
                ('date', models.CharField(blank=True, max_length=200, verbose_name='Course Date')),
            ],
        ),
    ]
