# Generated by Django 5.0.2 on 2024-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Test Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Test Description')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, verbose_name='Test Date')),
            ],
        ),
        migrations.AddField(
            model_name='coursedata',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Course Description'),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='date',
            field=models.DateField(blank=True, verbose_name='Course Date'),
        ),
    ]
