# Generated by Django 5.0.2 on 2024-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0002_courseassignmentscore_testdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.RemoveField(
            model_name='courseassignmentscore',
            name='test_id',
        ),
        migrations.AddField(
            model_name='courseassignmentscore',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
