# Generated by Django 5.0.2 on 2024-04-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0003_delete_testdata_remove_courseassignmentscore_test_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Test Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Test Description')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, verbose_name='Test Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseassignmentscore',
            name='course_id',
        ),
        migrations.AddField(
            model_name='courseassignmentscore',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
