# Generated by Django 5.0.2 on 2024-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0004_testdata_remove_courseassignmentscore_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('test_id', models.IntegerField(default=0)),
                ('score', models.FloatField()),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseassignmentscore',
            name='test_id',
        ),
        migrations.AddField(
            model_name='courseassignmentscore',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
