# Generated by Django 5.0.2 on 2024-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0006_appealdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealDataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
                ('content', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
