# Generated by Django 5.0.2 on 2024-05-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0007_appealdatatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealdata',
            name='state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appealdatatest',
            name='state',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
