# Generated by Django 5.0.2 on 2024-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_league', '0009_alter_appealdata_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealdatatest',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appealdatatest',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
