# Generated by Django 4.2.3 on 2024-03-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassTeamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Class Name"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Class Color ID"
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Class Slogan"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Class Desc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Season Name"
                    ),
                ),
                (
                    "startdate",
                    models.DateField(blank=True, verbose_name="Season Start Date"),
                ),
                ("enddate", models.DateField(verbose_name="Season Start Date")),
            ],
        ),
        migrations.CreateModel(
            name="MatchData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Match Name"
                    ),
                ),
                (
                    "isPastEvent",
                    models.BooleanField(default=False, verbose_name="Is A Past Event"),
                ),
                (
                    "a_score",
                    models.IntegerField(blank=True, verbose_name="Class A Score"),
                ),
                (
                    "b_score",
                    models.IntegerField(blank=True, verbose_name="Class B Score"),
                ),
                (
                    "a_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="A_Class",
                        to="league.classteamdata",
                        verbose_name="A Competitor Info",
                    ),
                ),
                (
                    "b_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="B_Class",
                        to="league.classteamdata",
                        verbose_name="B Competitor Info",
                    ),
                ),
            ],
        ),
    ]
