# Generated by Django 4.2.3 on 2024-03-29 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchdata",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Match Start Time",
            ),
            preserve_default=False,
        ),
    ]
