# Generated by Django 5.1 on 2024-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='time',
            field=models.DateTimeField(blank=True, default='2024-08-11 23:20:45', verbose_name='Match Start Time'),
        ),
    ]
