# Generated by Django 5.0.2 on 2024-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguedata',
            name='name',
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='end_time',
            field=models.DateTimeField(default='2002-09-01', verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='score_A',
            field=models.IntegerField(default=0, verbose_name='Score A'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='score_B',
            field=models.IntegerField(default=0, verbose_name='Score B'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='start_time',
            field=models.DateTimeField(default='2002-09-01', verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='team_A',
            field=models.CharField(default='Team A', max_length=200, verbose_name='Team A'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='team_B',
            field=models.CharField(default='Team B', max_length=200, verbose_name='Team B'),
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='League Title'),
        ),
    ]
