# Generated by Django 5.1 on 2024-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_matchdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='time',
            field=models.DateTimeField(blank=True, default='2024-08-11 23:30:34', verbose_name='Match Start Time'),
        ),
    ]
