# Generated by Django 5.0.2 on 2024-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_leaguedata_name_leaguedata_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='title',
            field=models.CharField(default='Untitled League', max_length=200, verbose_name='League Title'),
        ),
    ]
