# Generated by Django 5.0.2 on 2024-04-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_leaguedata_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguedata',
            name='point',
        ),
    ]
