# Generated by Django 5.0.2 on 2024-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_leaguedata_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='visibility',
            field=models.IntegerField(default=1, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='title',
            field=models.CharField(blank=True, default='Untitled League', max_length=200, verbose_name='League Title'),
        ),
    ]
