# Generated by Django 5.1 on 2024-08-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_matchdata_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchData',
        ),
    ]
