# Generated by Django 5.1 on 2024-08-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_delete_matchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Match Name')),
                ('isPastEvent', models.BooleanField(default=False, verbose_name='Is A Past Event')),
                ('a_score', models.IntegerField(blank=True, verbose_name='Class A Score')),
                ('b_score', models.IntegerField(blank=True, verbose_name='Class B Score')),
                ('time', models.DateTimeField(blank=True, default='2024-08-12 00:02:50', verbose_name='Match Start Time')),
                ('a_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_Class', to='league.classteamdata', verbose_name='A Competitor Info')),
                ('b_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_Class', to='league.classteamdata', verbose_name='B Competitor Info')),
            ],
        ),
    ]
