# Generated by Django 5.1 on 2024-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_matchdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='time',
            field=models.DateTimeField(blank=True, default='2024-08-18 17:49:19', verbose_name='Match Start Time'),
        ),
    ]
