# Generated by Django 5.1 on 2024-08-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Score Event Name')),
                ('point', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator Info')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDataChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Information')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_addition', models.DateField(verbose_name='Date Data')),
                ('date_of_activity', models.CharField(max_length=200, null=True, verbose_name='Date Data')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('score_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.scoreeventdata', verbose_name='Score Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Information')),
            ],
        ),
    ]
