# Generated by Django 4.2.3 on 2023-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0003_alter_studentscoredata_date_of_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentscoredata",
            name="date_of_activity",
            field=models.CharField(max_length=200, null=True, verbose_name="Date Data"),
        ),
        migrations.AlterField(
            model_name="studentscoredata",
            name="desc",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Description"
            ),
        ),
    ]
