# Generated by Django 4.2.3 on 2024-01-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0004_alter_studentscoredata_date_of_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentscoredata",
            name="checked",
            field=models.BooleanField(default=False, verbose_name="Checked"),
        ),
    ]
