# Generated by Django 4.2.3 on 2024-01-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0006_remove_studentscoredata_checked_studentdatachecker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdatachecker",
            old_name="checked",
            new_name="data_checked",
        ),
    ]
