# Generated by Django 5.0.2 on 2025-02-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Record Name')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name='Record Desc')),
            ],
        ),
        migrations.CreateModel(
            name='RecordHolderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Student Name')),
                ('s_class', models.CharField(blank=True, max_length=200, verbose_name='Student Class')),
                ('visibility', models.BooleanField(default=False, verbose_name='Visibility')),
                ('time', models.DateTimeField(blank=True, default='2025-02-25 23:22:35', verbose_name='Record Time')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='record.recorddata', verbose_name='Record')),
            ],
        ),
    ]
