# Generated by Django 5.0.2 on 2025-02-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordholderdata',
            name='related_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='record.recorddata', verbose_name='Related Record'),
        ),
        migrations.AlterField(
            model_name='recordholderdata',
            name='record',
            field=models.CharField(blank=True, max_length=200, verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='recordholderdata',
            name='time',
            field=models.DateTimeField(blank=True, default='2025-03-01 00:12:11', verbose_name='Record Time'),
        ),
    ]
