# Generated by Django 5.0.2 on 2025-04-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_recordholderdata_related_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddata',
            name='type',
            field=models.CharField(default='体育之最', max_length=200, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='recordholderdata',
            name='time',
            field=models.DateTimeField(blank=True, default='2025-04-04 10:18:23', verbose_name='Record Time'),
        ),
    ]
